swagger: "2.0"
info:
  version: 1.0.0
  title: activitypub.js
  description: An opinionated, practical and useful implementation of the ActivityPub spec
basePath: /
tags:
  - name: WebFinger
    description: WebFinger endpoints
  - name: ActivityPub
    description: ActivityPub related endpoints

consumes:
  - application/json
produces:
  - application/json

definitions:
  WebFinger:
    type: object
    title: webfinger
    required:
      - subject
      - links
    properties:
      subject:
        type: string
        description: The example name
      links:
        type: array
        description: Object containing rel, type and href descriptors
  Actor:
    type: object
    title: actor
    required:
    - '@context'
    - id
    - type
    - inbox
    - outbox
    properties:
      '@context':
        type: array
        description: JSON-LD context
      id:
        type: string
        description: Globally unique URI to this doc
      type:
        type: string
        description: object type
      inbox:
        type: string
        description: URI to the user's inbox
      outbox:
        type: string
        description: URI to the user's outbox
      # TODO: add all properties listed here: https://www.w3.org/TR/activitypub/#actor-objects
  ASObject:
    type: object
    title: activity-streams-object
    required:
      - '@context'
      - type
    properties:
      '@context':
        type: string
        description: JSON-LD context
      type:
        type: string
        description: object type (link, activity etc.)
      id:
        type: string
      actor:
        type: string
      object:
        type: object
      #  TODO: add all properties listed here: https://www.w3.org/TR/activitystreams-vocabulary/#types


paths:
  .well-known/webfinger:
    get:
      tags:
        - WebFinger
      parameters:
        - name: resource
          in: path
          required: true
          description: The account username to query
          type: string
          schema: 
            $ref: "#/definitions/WebFinger"
      responses:
        200:
          description: Return the resource
        400:
          description: Malformed request
        404:
          description: Resource not found
  users/{preferredUsername}:
      get:
        summary: Get a user's actor
        tags:
          - ActivityPub
        parameters:
          - name: preferredUsername
            in: path
            type: string
            required: true
            schema:
              $ref: "#/definitions/Actor"
        responses:
          200:
            description: Return the user
          400:
            description: Malformed user name
          404:
            description: User not found
  users/{preferredUsername}/inbox: # TODO finish spec
    get:
      summary: Get a user's inbox
      tags:
        - ActivityPub
      parameters:
        - name: preferredUsername
          in: path
          type: string
          required: true
          schema:
            $ref: "#/definitions/Actor"
      responses:
        200:
          description: Return the user's inbox
        400:
          description: Malformed user name
        404:
          description: User not found
    post:
      summary: Send a message to a user's inbox
      consumes:
        - application/json
      responses:
        201:
          description: Created
        400:
          description: Malformed user name
        404:
          description: User not found     
      tags:
        - ActivityPub
      parameters:
        - name: preferredUsername
          in: path
          type: string
          required: true
        - name: activity-streams-object
          in: body
          description: Activity-streams-object to add to the user's inbox
          required: true
          schema:
            $ref: '#/definitions/ASObject'